### ISSUE TITLE
How to use testbench build

### ISSUE THREAD

**Issue by howard0su** [threeme3/QCX-SSB#17]
I saw the code but I cannot figure out how to use it.

**Comment by threeme3** [comment]
Hi Howard,

The testbench can be enabled by adding:
`#define TESTBENCH     1`

What it does is that it inject a sine/cosine wave on the I/Q inputs. This is good for testing the receiver chain to see if there are spurious responses or overload cases. Currently I am using a TinySA instrument to inject such signals and find this versatile way test the receiver.

Guido
