### ISSUE TITLE
Dead audio when using VOX with SSB mods

### ISSUE THREAD

**Issue by phckopper** [threeme3/QCX-SSB#2]
Hello,
I've finally made this project work on my QCX and performed only the SSB modifications. What I noticed is that, when VOX is enabled, the RX audio disappears (just noise), even when VOX isn't triggered (V showing on LCD, not transmitting). I'm running v1.02a and my RX audio works normally when VOX is disabled.

**Comment by threeme3** [comment]
Hi Pedro,
Very good to hear you got the SSB mod working on your QCX! And many thanks for reporting on the VOX issue when only SSB mod is made. I have found the bug and re-uploaded the fix in R1.02a release, and it will solve your issue. 73, Guido

**Comment by phckopper** [comment]
Thank you, Guido! Your mod is awesome and made my QCX spring back to life. You're awesome, if I could I'd buy you a beer :smile:
