### ISSUE TITLE
Extreme redundancy of LCD updates when menumode > 0

### ISSUE THREAD

**Issue by adrianboyko** [threeme3/QCX-SSB#34]
Hi! When menu mode is > 0, the following code in loop() updates the LCD on _every_ iteration. Could you make the update happen only when it's actually required? I'm experimenting with a display option that would greatly benefit from not being overwhelmed by redundant LCD updates.

```
  bool param_change = (encoder_val != 0);
  if(menumode != 0){  // Show parameter and value
    if(menu != 0){
      paramAction(UPDATE_MENU, menu);  // update param with encoder change and display
```

I tried a version that defined some new change conditions and added an `if (param_change || menumode_change || menu_change)` before the `paramAction` call, but I'm not confident that I understand the loop logic well enough to submit it as a reasonable pull request.

**Comment by threeme3** [comment]
Hi Adrian,
Thanks for the suggestion!
Updates now should only happen when parameters are changed, or when stepping into the menu.
An exception are menu items 9.1 to 9.3 which will be kept refreshed when entering.
You can find the change into the unreleased branch https://github.com/threeme3/QCX-SSB/blob/feature-rx-improved/QCX-SSB.ino
