### ISSUE TITLE
Entry into menumode 1 only displays correctly on first entry.

### ISSUE THREAD

**Issue by adrianboyko** [threeme3/QCX-SSB#39]
Repro steps:

1. Start uSDX
2. Press left button
3. Note that `1.1 Volume` and `+12` are displayed indicating that menu mode 1 has been entered.
4. Press right button
5. Note that we're now in menu mode 0, according to display.
6. Press left button (and resist urge to press it again if you don't get what you expect)
7. Note that display does not change.
8. Press left button
9. Note that `1.1 Volume` and `>+12` is displayed indicating that menu mode 2 has been entered.

I believe this is happening because `prev_menumode` is initialized to 0 but never ever returns to 0 because it's only ever changed inside an `if (menumode != 0)`. As a result, going into menu mode 1 results in a correct display update only the first time the left button is pressed.

**Comment by threeme3** [comment]
Thanks you Adrian for this very clear bug report and analysis.
Your analysis is correct. I have made a change, that whenever a menumode is changed, the menu is updated.
