### ISSUE TITLE
Delay lines

### ISSUE THREAD

**Issue by crazyimp** [threeme3/QCX-SSB#4]
Hi Guido,
the delay lines may include a bug or an extra element which can be removed.
For example: https://github.com/threeme3/QCX-SSB/blob/1e97ccae49598a3068d1127e87b88c947348909b/QCX-SSB.ino#L1810-L1813

The current value gets written into `v[7]` but in the end, `v[7]` is also copied into `v[6]` causing the delay line to be shortened to 7 elements instead of 8. If the lines 1811 and 1813 would be swapped, we would get a delay line with 8 elements. Or cut the array to 7 elements and go with `i = v[0]; v[0] = v[1]; v[1] = v[2]; v[2] = v[3]; v[3] = v[4]; v[4] = v[5]; v[5] = v[6]; v[6] = ac2 >> att2;` - dunno what is intended here :).

Same applies to:
https://github.com/threeme3/QCX-SSB/blob/1e97ccae49598a3068d1127e87b88c947348909b/QCX-SSB.ino#L1870-L1873
https://github.com/threeme3/QCX-SSB/blob/1e97ccae49598a3068d1127e87b88c947348909b/QCX-SSB.ino#L1963-L1966
https://github.com/threeme3/QCX-SSB/blob/1e97ccae49598a3068d1127e87b88c947348909b/QCX-SSB.ino#L1984-L1987

73, DC1MP

**Comment by threeme3** [comment]
Hi DC1MP. Many thanks for this observation!
You are correct that one element can be saved, much appreciated.
I have made a code change.
Thanks, 73!
