### ISSUE TITLE
Main screen banner is overwritten by decoded CW after switching off CW decoder

### ISSUE THREAD

**Issue by adrianboyko** [threeme3/QCX-SSB#40]
Minor issue:

1. Power on uSDX
2. Go to CW Decoder setting and switch ON
3. Return to main screen
4. Allow decoded characters to accumulate
5. Go to CW Decoder setting and switch OFF
6. Return to main screen

What's wrong: When returning to the main screen in the final step, the "uSDX▶" banner briefly appears but is immediately overwritten by the previously decoded CW data.

**Comment by threeme3** [comment]
Tnx! 
Yes, some outstanding event was still triggering writing. It is now fixed.
Guido

**Comment by threeme3** [comment]
oops..forgot to push to code to github, now fix is there
