### ISSUE TITLE
Uncommenting "#define MOX 1" results in compile errors.

### ISSUE THREAD

**Issue by adrianboyko** [threeme3/QCX-SSB#42]
In order to re-enable MOX, I uncommented the `#define MOX 1` line. Unfortunately, this leads to compile errors, presumably because the symbol `MOX` is used in the definition of `enum params_t`. Perhaps change `#define MOX 1` to `define MOX_ENABLED 1` and change the corresponding `#ifdef MOX` directives to `#ifdef MOX_ENABLED`?

**Comment by threeme3** [comment]
Thanks Adrian.
