### ISSUE TITLE
AGC low volume bug

### ISSUE THREAD

**Issue by jokubasver** [threeme3/QCX-SSB#43]
Seems like sometimes the AGC does not recover. The easiest way I found to reproduce this bug is to quickly switch between all ham bands by double clicking the rotary encoder. The volume will become very low. Power cycling the radio brings the volume back to normal levels. 

Tested on latest feature-rx-improved firmware.

**Comment by ImzFan** [comment]
It is strange this behaviour, but had the same experience on actual Version "1.02r".

**Comment by jokubasver** [comment]
I haven't experienced this issue for a while now, so it's probably fixed. Closing the issue.
