### ISSUE TITLE
In the receive description of the README, I think Q6 is a typo, and it should be Q5.

### ISSUE THREAD

**Issue by frohro** [threeme3/QCX-SSB#46]
The sentence where I believe Q6 should be Q5 is:
 

> Three embedded attenuators are available for optimally using dynamic range; the first attenuator is the RX MOSFET switch Q6 responsible for 20dB attenuation, the second attenuator is ADC range (1.1V or 5V) selected by the ATMEGA ADC analog reference (AREF) logic and is responsible for 13dB attenation, the third attenuator is a pull-down of an analog input on the ATMEGA with a GPIO port responsible for 53dB attenation.

Rob

**Comment by threeme3** [comment]
Rob,
Yes! I fix fixed that typo. Many thanks for this catch.
Enjoy the project, 73
Guido
