### ISSUE TITLE
Is the assembly PDF v 1.01 missing XTAL2 in checklist on page 2?

### ISSUE THREAD

**Issue by caseyjamesdavis** [threeme3/QCX-SSB#5]
Fantastic project!

Just starting my QCX-SSB build.

Cheers,
Casey
KC1JHV

**Comment by threeme3** [comment]
Hi Casey!

Good catch. Manuel has updated the document and I have just uploaded it. Tnx!
Let us know if you have more findings.
Enjoy the build.
73 Guido

**Comment by caseyjamesdavis** [comment]
Hi Guido!

I finished mine yesterday and it works great!

![IMG_1526](https://user-images.githubusercontent.com/49321778/82665193-4d0fc180-9c01-11ea-9d46-831c04d8f7fc.jpg)

I do have a few more findings for the assembly manual.  What is the best way for me to share them with you (this gh issue, new gh issue, email, groups.io)?

73
Casey

**Comment by threeme3** [comment]
Wow.. Great! Looks very good, and very happy it is working great.

Yes, the best is to pass the comments to Manuel DL2MAN, so he can take these findings in the next version of the assembly manual. You can send him privately in the forum. You can also pass the comments here and I will forward to him. Up to you whats the best for you.
Thanks gain, and enjoy your new transceiver :-)

**Comment by caseyjamesdavis** [comment]
I will send directly to Manuel.

Thank you for sharing such an interesting and useful project.

73
Casey
